apiVersion: v1
kind: Service
metadata:
  name: project-posted
spec:
  selector:
    app: project-posted
  ports:
    - name: app-metrics
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: tunnel-metrics
      protocol: TCP
      port: 5000
      targetPort: 5000